Add create branch
Yagni-Inc/yagni pull request #4
Opened 2022-02-12 22:02 UTC by KyleZim97

Please ignore the first file Add.Java. I don't know how to remove it.

The second file I am pushing the Menu.java includes the new method AddRecord that adds records to the inventory file and includes some edits to main. These edits include removal of the try block for the user selection, changed the scanner name to scInput and general formatting of main which I mostly edited indentation.

2022-02-12 22:14 UTC, KyleZim97 commented
![](https://github.trello.services/images/mini-trello-icon.png) ["Create" functionality](https://trello.com/c/FRi60d6H/2-create-functionality)

2022-02-12 22:46 UTC, chillyssa requested changes
To not include this file, just delete it from your end on local and recommit to this branch and it should delete in the pull request. 

The Main  Menu looks great! Glad to see our functionality coming together

2022-02-12 22:51 UTC, chillyssa approved these changes
Looks great! Thanks for removing it!

2022-02-13 03:23 UTC, snowjtSD approved these changes
looks fine to me I will build the update method and by tomorrow morning i will hope to have the final name for the delete function since the current update functionality is just the delete followed by the add method for this sprint and the next sprint update will be expanded much more for proper curation of the fields.

2022-02-13 03:24 UTC, snowjtSD commented
looks fine to me!

2022-02-13 03:24 UTC, snowjtSD approved these changes

2022-02-13 17:10 UTC, chillyssa requested changes

2022-02-13 17:10 UTC, chillyssa commented on Menu.java
> +  public void AddRecord(){
@KyleZim97 I just realized - since this is a method, not a class, we need to define it with a lower case a- so addRecord() should be the method name. Are you able to make this change before we merge to main?

2022-02-13 19:20 UTC, KyleZim97 commented
I accidentally commited with just an o. fat fingered something but  I changed the name of the method AddRecord to addRecord to be more consistent with naming conventions.

2022-02-13 19:24 UTC, chillyssa approved these changes
Great! We are going to need to move this into Main.java once that PR is approved but thank you for updating the method!

2022-02-13 20:51 UTC, S4kRiPp4 approved these changes
only questions/concerns were with the strInput.nextLine(s) Line 78, 82,86,90.

was just wondering if we would need those to be input.NextFloat();? to accept lets say a sale cost of $75.99? I don't know if I'm over thinking. 

Other than that everything looks great, good job Kyle.

2022-02-13 21:11 UTC, merged